### ISSUE TITLE
remotelogger module not found

### ISSUE THREAD

**Issue by IT-Berater** [kanflo/ADS-B-funhouse#1]
Hi,

i can not use **adsbclient.py** i have no remotelogger modul. I start the script, and this Error:

`remotelogger module not found, install from github.com/kanflo/python-remotelogger`

How can download the logger? I use Raspberry Pi, weezy (http://blog.wenzlaff.de/?s=dump1090)

Greetings

Thomas

**Comment by kanflo** [comment]
Hi Thomas,

Sorry about that. This is due to sloppiness on my side. I am currently traveling but you should be able to get the scripts running by simply removing the `import remotelogger` lines at the top and the call to `remotelogger.init`. I will fix and push this when I return home and have access to my ADS-B infrastructure :) On a side note, the remote logger is being replaced with fluentd which seems to be a nice alternative to remote logging on headless nodes.

Cheers,
Johan

**Comment by IT-Berater** [comment]
Hi Johan,
i remove the log code and its going well :-) 

Have a great holiday yet.

Greetings Thomas

**Comment by IT-Berater** [comment]
The same in proxclient.py

**Comment by kanflo** [comment]
Thanks Thomas. I will leave this issue open until I have updated the scripts.

**Comment by theSC** [comment]
Hello.  I am wondering if this will be updated?  I am struggling with the same issue but can't seem to figure out how to disable the module

**Comment by kanflo** [comment]
Closed by #3644d4324a
